runtime: nodejs14
env: standard
instance_class: F1
automatic_scaling:
  min_instances: 1
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:
  - url: /static
    static_dir: build/static

  - url: /public
    static_dir: public

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$

  - url: /(.*\.(jpg|jpeg|png|gif|svg))$
    static_files: public/\1
    upload: public/.*\.(jpg|jpeg|png|gif|svg)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html

env_variables:
  PUBLIC_URL: "/public/"
