DROP TYPE IF EXISTS INTERACTION_TYPE CASCADE;
CREATE TYPE INTERACTION_TYPE AS ENUM ('edit', 'delete', 'change_audience');

CREATE TABLE IF NOT EXISTS user_actions (
  user_id INTEGER PRIMARY KEY,
  post0 INTERACTION_TYPE,
  post1 INTERACTION_TYPE,
  post2 INTERACTION_TYPE,
  post3 INTERACTION_TYPE,
  post4 INTERACTION_TYPE,
  post5 INTERACTION_TYPE,
  post6 INTERACTION_TYPE,
  post7 INTERACTION_TYPE,
  post8 INTERACTION_TYPE,
  post9 INTERACTION_TYPE,
  post10 INTERACTION_TYPE
);